### PR TITLE
Ported Coding Challenge 167 Prime Spiral to Processing

### PR DESCRIPTION
**Pull request by spencerstith**
### Community Contribution

Ported Coding Challenge 167 to Processing. I had to move the P5 versions into their own folder and made a Processing folder to put the ports in. Translation didn't change much in the logic, except for some minor adjustments in `prime-random`, where I had to use a boolean as the parameter to Spiral's update method rather than a function like in the P5 version. I could have made it work somehow by using `Callable` and a method reference, but that didn't feel very natural to do in Processing, so I just passed a `isRandom` value to the update function.

I ported all 5 versions. Here are screenshots of each of them working.

---
number-spiral

prime-random

prime-spiral

shapes-color

spiral-3d

Unfortunately, I could quite get the specular lighting to work in the Processing version since there is a good amount more you have to do to make it work compared to in P5.

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**

**Twitter:**

### CODE REVIEW

**Comment by spencerstith** [comment]
I am not certain whether the new folder structure was the correct way to do it, but I believe I am close after viewing the structure in other coding challenge directories. Please correct it if needed and let me know how it is supposed to be for future reference.

**Comment by KobeLiesenborgs** [comment]
Hey @spencerstith ! 
Thank you for making these ports and contributing them to the website! 
Unfortunately it seems like you tried to edit the structure that's used for Dan's own examples from the videos, to add your own versions as community contributions please follow this guide instead: https://thecodingtrain.com/Guides/community-contribution-guide.html
Let me know if you need any more info/help!

**Comment by spencerstith** [comment]
Good morning! Do you think you could be a bit more specific? I ported all 4 versions that were implemented in P5 on the website, and used the web editor to make sure my results were identical. I did have to slightly change the code's structure to follow the coding conventions of Java/Processing (ie moving the classes into separate files and not having it all in one). Processing also doesn't allow methods to accept functions as parameters, so I did have to change that as well, but only changed one parameter from a function to a boolean value. I apologize if this should not have been done however. If you tell me what I did wrong, I will fix the mistakes and retry!

**Comment by spencerstith** [comment]
I believe there is a misunderstanding - I am not making a contribution of my own code or variation of a coding challenge. This repository has asked for help in porting all of Dan's coding challenges to other languages (#1347). Dan implemented these 4 things himself in P5 and they are  [on the site as his own code](https://thecodingtrain.com/CodingChallenges/167-prime-spiral.html). I am helping the site by porting what he did to the Processing language, so that his challenges can be seen in P5 and in Processing. This will show up on the site as source code, just in the Processing language, [such as here](https://thecodingtrain.com/CodingChallenges/146-rendering-ray-casting.html), where I ported his P5 code to Processing as well. I believe the title of this PR being "Community Contribution" was misleading and a mistake.

**Comment by KobeLiesenborgs** [comment]
@spencerstith thank you for the contribution! I didn't realise that's what you were helping out with!

**Pull request merged**
