### PR TITLE
Added caching to circleci testing

### PR DESCRIPTION
**Pull request by gruselhaus**
Hi,

@nilsweb can you review this https://circleci.com/gh/gruselhaus/codingtrain-website/20 please and give me some feedback?

#### FYI: Caching shortens the total runtime to about 1/3.

@shiffman What do you think about that?

### CODE REVIEW

**Comment by gruselhaus** [comment]
Why does circleci not check my changes?

**Comment by nilsweb** [comment]
Yay, really cool! :tada:

Some thoughts:
- Maybe we could also cache the node modules used for testing to speed things up?
- Same thing with the source code? Downloading all those coding challenges over and over again seems a little bit unnecessary...

Have you already taken a look at this guide? https://circleci.com/docs/2.0/caching

It could be that Circle CI runs into some problems because the test configuration changed and it tries to use those? I also don't really know what's going on...

**Comment by shiffman** [comment]
Thanks for working on this, would be great to speed this up, yes!

**Comment by gruselhaus** [comment]
> Yay, really cool! 🎉
> 
> Some thoughts:
> 
> * Maybe we could also cache the node modules used for testing to speed things up?
> * Same thing with the source code? Downloading all those coding challenges over and over again seems a little bit unnecessary...
> 
> Have you already taken a look at this guide? https://circleci.com/docs/2.0/caching
> 
> It could be that Circle CI runs into some problems because the test configuration changed and it tries to use those? I also don't really know what's going on...

@nilsweb Thank you for your suggestions. I have implemented these now.
See: https://circleci.com/gh/gruselhaus/codingtrain-website/31

**Comment by nilsweb** [comment]
Yes! Awesome! :tada:
From what I've seen, we went down from about two minutes to just 15 seconds! :+1:
Let's merge and see how it goes!

> This should be the fix: https://circleci.com/docs/2.0/workflows-waiting-status/

I don't have permissions to change the repository settings. Maybe @shiffman can look into this?

**Comment by gruselhaus** [comment]
@nilsweb I think I found the bug. I had set up my own project for the repo on CircleCi and CircleCi could not differentiate between the configuration files. I think I could fix it now. I will close this pull request now and open a new one.

**Comment by shiffman** [comment]
This is amazing, thank you @nilsweb and @gruselhaus!

**Pull request closed without merging**
