### PR TITLE
darken some colors to meet WCAG AA

### PR DESCRIPTION
**Pull request by phucduong86**
Nav Before:
image
Nav After:
image

Button before and after:
image
image

image
image

Before:
image

After:
image

Before:
image
After:
image

### CODE REVIEW

**Comment by phucduong86** [comment]
Also added focus style (replicated hover) for buttons to make it more visible.

**Comment by shiffman** [comment]
This looks great to me! Design-wise I don't want to be picky but for the nav if there's a way to change the text color or pick something a bit more blu-ish that blends with the background sky that might be a little better?

**Comment by phucduong86** [comment]
> This looks great to me! Design-wise I don't want to be picky but for the nav if there's a way to change the text color or pick something a bit more blu-ish that blends with the background sky that might be a little better?

Hmm changing the text color will affect mobile look. Maybe I'll merge this in and play with the color when I work on the mobile nav?
image

**Comment by phucduong86** [comment]
This is a little more blue if you want:
image

**Comment by phucduong86** [comment]
That looks great @nilsweb.
I'll put that on the todo list.

**Comment by nilsweb** [comment]
I've just taken a look at the live page. Looks great! Only thing I'm missing is a hover style for the links in the navigation bar, like a color fade, pop, etc.. Maybe when we use the "bookmarks", they can pull down on hover? Just putting it here so we don't forget.

**Pull request merged**
