### PR TITLE
Added python implementation

### PR DESCRIPTION
**Pull request by se7enA**

### CODE REVIEW

**Comment by shiffman** [comment]
Please submit your version using the new system! 

https://github.com/CodingTrain/website/wiki/Community-Contributions-Guide

Apologies for this confusion, the existence of these README's is still causing confusion. #400

**Comment by se7enA** [comment]
What do you mean? I followed the same wiki.
Sorry I'm new to github, so I don't know much about it

**Comment by shiffman** [comment]
I'm so so sorry in my haste reviewing these I somehow thought this was a change to an old README! But it's not! It is done totally correctly! I see you submitted a new pull request #502 so I'll move the discussion to there. My apologies again!

**Comment by se7enA** [comment]
Yeah, no problem

**Pull request closed without merging**
