### PR TITLE
Maze Generator: hexagons instead of squares

### PR DESCRIPTION
**Pull request by sylvainberube**
Link to demo here: https://editor.p5js.org/sylvainberube/full/doxwlc9US

### CODE REVIEW

**Comment by sylvainberube** [comment]
First pull request on github for The Coding Train, hope I got it right.

**Comment by gruselhaus** [comment]
This is so cool!

**Comment by shiffman** [comment]
Wow, this is amazing! Are you on instagram? Maybe we can feature it?

**Comment by sylvainberube** [comment]
Thanks for the positive retroaction and for the inspiration too!

I'm not active on Instagram no. Feel free to feature the project wherever you want.

**Pull request merged**
