### PR TITLE
CC_146_Rendering_Ray_Casting: fixed fisheye problem

### PR DESCRIPTION
**Pull request by karlphillip**
This PR completely fixes the fisheye problem in **CC_146_Rendering_Ray_Casting**.

### Community Contribution

**Link to live project, video, or image:**
https://imgur.com/a/LcawcHU

**Twitter:**
[@karlphillip](https://twitter.com/karlphillip)

### CODE REVIEW

**Comment by karlphillip** [comment]
@shiffman 
This is more like a **bug fix** and not really a **community contribution** like I've seen others do by addingtheir own implementations separately.

The result is Raycasting without the fisheye problem. I shared the link to a GIF on the PR but I've also implemented this technique in QML on my repo:
[](https://github.com/karlphillip/GraphicsProgramming/tree/master/qml2DRaycastingEngine)

There's a cooler GIF there.

**Comment by shiffman** [comment]
Oh awesome, this is wonderful! Would you mind adding a code comment by the changes to help anyone who is coming to see the code after watching the video? Perhaps it could also include the original code from the video commented out?

**Review by shiffman — APPROVED** [review]
Awesome! Thank you! (although I guess there are some linting errors to be fixed)

**Comment by karlphillip** [comment]
I will try to fix them shortly.

**Pull request merged**
