### PR TITLE
[New Feature] Adding tags to website

### PR DESCRIPTION
**Pull request by chepecarlos**
To make it easier to find and organize content add tags to website content and youtube video description for better SEO

### things done
- tag Layouts 
- funcion tag
- page tag
- tag generator function
- tag cloud
- tag youtube description

### to do
- Update guide
- Add more tags
- clean the code more

use the generate-youtube-descriptions.js code as a base to generate the tag pages and the tag cloud

Sorry my bad english

### Community Contribution

**Link to live project, video, or image:**

imagen

imagen
imagen
imagen

### Sharing

- [X] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:** ALSWnet

**Twitter:** ALSWnet

**Youtube:** ALSWnet

### CODE REVIEW

**Comment by gruselhaus** [comment]
I love this. Maybe we should incorporate this idea into the new system as well. @shiffman @violetcraze

**Comment by gruselhaus** [comment]
@chepecarlos the branch `pr#233103/ci-fix ` holds the fix for the failed CI workflow. Could you merge this branch into yours please.

**Comment by shiffman** [comment]
Oh this is fantastic!!! A new website design and build system is slated to be developed this coming May! I'm happy for this to be incorporated in the meantime and for us to keep all of the data / tags for the next iteration. But I don't want anyone to feel they have put a ton of work into something to have it changed. What do you all think? Thank you so much for this wonderful contribution @chepecarlos!!

**Comment by KobeLiesenborgs** [comment]
@chepecarlos I'm sorry to see this got lost in the neverending stream of pull requests! 
I fear we are pretty close to the new website being released at this point so it might not be worth updating this to match the current website now that we're almost a year further. 
Apologies that it took so long to get a response/update! We really appreciate it and hope to see more of your suggestions in the future!

**Pull request closed without merging**
