### PR TITLE
Added contribution

### PR DESCRIPTION
**Pull request by cspears1110**
Added Coding Challenge Contribution to 116-lissajous.md

### CODE REVIEW

**Comment by cspears1110** [comment]
Running example:
https://editor.p5js.org/full/ByNmpl_5m

I'll check to see what's wrong with the yaml

**Comment by cspears1110** [comment]
I've run it through a validator, it says it's valid yaml. The file is supposed to have a newline at end of file, correct? I'm following the contributions guide, as well as looking at previous submissions.

**Comment by shiffman** [comment]
Hmmm, not sure! Maybe @nilsweb can help?

**Comment by cspears1110** [comment]
There we go, all fixed!

**Comment by shiffman** [comment]
Yay!

**Pull request merged**
