### PR TITLE
New Video! Pose Classification

### PR DESCRIPTION
**Pull request by shiffman**
This should be the markdown file, still to do is add the code to a "repo" folder here, I'm only pointing to the web editor. Also, this one is different in the sense that there are actually three sketches! I combined them all into one and linked that as the "web editor" sketch but then added links to the individual sketches as well. Plan to make this public tomorrow (Wed) morning! (It's "members only" at the moment.)

https://youtu.be/FYgYyq-xqAw

Any feedback on thumbnail welcome!

ymca

### CODE REVIEW

**Comment by gruselhaus** [comment]
@shiffman I've added the source code.

**Comment by shiffman** [comment]
@gruselhaus looks like some extra commits or conflicts were introduced perhaps?

**Comment by shiffman** [comment]
oh, i see! it was a bunch of linting things! Is this ok to merge?

**Comment by gruselhaus** [comment]
@shiffman yes, will fix the linting issues later on.

**Comment by gruselhaus** [comment]
@shiffman please do not use squash merge so I can get the differences related to the linting issues

**Comment by shiffman** [comment]
sure thing! But I am planning to release the video this morning and would like the web page up. Should I just start a new pull request or can we revert the extra commits?

**Pull request merged**
