### PR TITLE
Coding Challenge Variations Gist

### PR DESCRIPTION
**Pull request by gruselhaus**

### CODE REVIEW

**Comment by gruselhaus** [comment]
https://gist.github.com/gruselhaus/368d87bf4e3558f01292e8c00afda224

**Comment by shiffman** [comment]
Thank you for this work! Looks great! Can you remind me the feature this implements? ❤

**Comment by gruselhaus** [comment]
Currently there's a [file](https://github.com/CodingTrain/website/blob/master/CodingChallenge_Variations.md ) located in the root of this repo that shows you all CC and their Versions. But at this moment you have to run the script manually. If we run the script along with the current CI procedures the file would be updated every time the CI task is triggered.

**Comment by gruselhaus** [comment]
@shiffman Unfortunately this PR can only be merged from an Administrator, because the CI Config has been changed. For reference: I run the tests on my forked. They passed.  
https://circleci.com/gh/gruselhaus/website/51

**Comment by shiffman** [comment]
Merged!!

**Comment by gruselhaus** [comment]
Thank you !

**Pull request merged**
