### PR TITLE
resolve #1053 pages for beginner's guide to ml5

### LINKED ISSUE #1053: pages for beginner's guide to ml5
I'd love to create pages on the site like the coding challenges for the beginner's guide to ml5 videos. This would help me compile projects and contributions from the community related to these videos. If anyone has some time to help out with this, please feel free to jump in! Related #1051.

### PR DESCRIPTION
**Pull request by JMackie80**
### Community Contribution

**Link to live project, video, or image:**
https://drive.google.com/file/d/1g8KOWsrRmn9MHw1XiieN89vwJUlpNq7m/view?usp=sharing

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

### CODE REVIEW

**Comment by shiffman** [comment]
Wow, thank you for working on this!!

**Comment by GypsyDangerous** [comment]
#1053

**Comment by violetcraze** [comment]
I forgot that the courses section has community contributions turned off by default. So to override that you can to add the line `can_contribute: true` in the markdown files.

**Comment by JMackie80** [comment]
Thanks for the feedback. Sorry for the confusion. Please let me know if any further changes are needed. Thanks for the great work you all are doing!

**Comment by violetcraze** [comment]
Sorry it took me so long to follow up. I might have been unclear about the structure. I was thinking of something like the [data and apis directory](https://github.com/CodingTrain/website/tree/master/_Courses/data-and-apis). So would look something like ` _Courses/ml5-beginners-guide/0.0-ml5-beginners-guide.md`. No need to the directories for each set of videos in the the series. Sorry to be so picky it would just be nice if it matched the current structure, but really appreciate your work. If you're tired of moving and renaming files I'd be happy to do it just let me know.

**Comment by JMackie80** [comment]
Sorry about that. I didn't notice the ignore_filename option before.

**Comment by violetcraze** [comment]
Looks great! Thanks for all the work you put in!

**Pull request merged**
