### PR TITLE
 Coding Challenge 98: Add quadtree.md files and contribution

### PR DESCRIPTION
**Pull request by romibi**
**Added the following files based on info from Youtube videos:**
_CodingChallenges/98.1-quadtree.md
_CodingChallenges/98.2-quadtree.md
(The date in part 2 might need modification once the youtube video is listed.)

**Added my contribution with Mouse-Wheel control to range size**
For live example see https://alpha.editor.p5js.org/full/HkDKgnIcz
For Source see: https://github.com/romibi/p5.js-Playground/tree/master/CC_98_QuadTree

**Open Questions:**
- Are readme.md files in the CodingChallenges/ subfolders with contributions now unwanted or still welcome?
- Is that correct that contributions in these files always have to be in part 1?

### CODE REVIEW

**Comment by romibi** [comment]
of course feel free to only use the second commit and create the quadtree.md files yourself

**Comment by blinkityblank** [comment]
@romibi Thanks for those! Couple of notes that you can change before we merge:

- The links in the "Parts" sections have a mistake.
image
It should be `98.1`, not `97.1`

Also, when the challenge is made with JavaScript, you can remove the line `live_example: false` altogether. The repo is used as the live_example.

You can make those changes and I believe we're good to merge!

**Comment by romibi** [comment]
oh right …
fixed

what about my open questions from the PR's description?

**Comment by blinkityblank** [comment]
Thanks for the corrections.

For the multi-part: Yes, all the contributions only go in Part 1.
On whether or not we still accept README.md files in the Coding Challenges directories, I know that they are not necessary anymore, but I'll let @nilsweb give the official answer on that.

**Comment by nilsweb** [comment]
In my opinion, the readme files should only be used to add notes to the code itself and not for adding contributions, but for an official answer we have to ask @shiffman.

**Comment by shiffman** [comment]
Yes, the contributions should now live in the markdown web pages! Thanks @romibi and @nilsweb!

**Pull request merged**
