### PR TITLE
Added hover effect on .video-card

### PR DESCRIPTION
**Pull request by joerez**

### CODE REVIEW

**Comment by gruselhaus** [comment]
@joerez Thanks for that! I've corrected the syntax so that it can be successfully compiled. May I merge from your side?

## Preview:

jan-06-2019 16-38-57

**Comment by gruselhaus** [comment]
@nilsweb I added a restriction there. This should fix the problem.

**Comment by joerez** [comment]
Glad this ended up working out.

**Comment by gruselhaus** [comment]
@shiffman What do you think about it?

**Pull request merged**
