### PR TITLE
Code refactored and Moves implemented

### PR DESCRIPTION
**Pull request by vladig98**
I refactored the code so that all rotations are in one function. I've implemented the real moves of the Rubik's cube. Colors of the cube updated.

### CODE REVIEW

**Comment by shiffman** [comment]
I love this idea! Thank you for taking the time to do this work! I like to keep the code in this repo matching the video so that viewers can follow along. I just posted the same thoughts in #1282 but I'll repeat here anyway!

1. You could submit your own version as a [community contribution](https://github.com/CodingTrain/website/wiki/Community-Contributions-Guide).
2. I could create a community "Rubik's Cube" project separate from the website that viewers could develop. I like doing this, but it often becomes difficult to manage.

What do you think?

(I'll also note that I am releasing part 3 tomorrow).

**Comment by vladig98** [comment]
Hi Dan,

The reason behind this pull request is mostly the implementation of the moves and updating the colors. Also you said that you wanted to refactoring the rotation functions so I did that (not saying that this is the best way to do it but..... anyways it's there). So please think about implementing the moves for part 4 so that it will be easier once you try to do the AI (if you intend to use any algorithms of course). And yes I'll try to submit my version on the web.

Thank you
You're amazing.

**Comment by vladig98** [comment]
@shiffman I updated part 3. Please take a look.

**Comment by shiffman** [comment]
This is amazing! Could it be posted as a community contribution and linked from the challenge? Then I could refer to it if / when I continue the challenge.

**Comment by vladig98** [comment]
> This is amazing! Could it be posted as a community contribution and linked from the challenge? Then I could refer to it if / when I continue the challenge.

Yes, of course. But please do continue this series. The coding challenge turns out great. I know that the AI part might be difficult but you'll figure it out. You always do.

**Comment by shiffman** [comment]
I'd like to leave this open for a little while pending a new pull request with a link to the code this code or even just a diff? This will be a helpful reminder if/when I return to the project!

**Comment by vladig98** [comment]
3x3-logo
2x2
3x3
4x4
5x5
6x6
7x7

**Comment by gruselhaus** [comment]
Implemented along https://github.com/CodingTrain/website/pull/1373

**Pull request closed without merging**
