### PR TITLE
Update 021-mandelbrot-p5.md

### PR DESCRIPTION
**Pull request by theCCB**
Mandelbrot Set in Processing with Navigation
A Processing program to navigate in the mandelbrot set, magnify, change color etc.
Screenshots:
https://ibb.co/VBSZFLq
https://ibb.co/K5Dy5LS
https://ibb.co/RHxzhxp
https://ibb.co/5cYXqHy
https://ibb.co/zbgwBRw
https://ibb.co/wYQ9p9q

### CODE REVIEW

**Comment by GypsyDangerous** [comment]
also, adding a youtube link doesn't work, you have to use the video id.

**Comment by gruselhaus** [comment]
> also, adding a youtube link doesn't work, you have to use the video id.

That should work, because this links references to a channel and not to a video.

**Comment by GypsyDangerous** [comment]
Oh, I didn't realize that.

**Comment by gruselhaus** [comment]
@theCCB Reminder ⏰

**Comment by gruselhaus** [comment]
@theCCB Second Reminder ⏰

**Comment by ArtemSer** [comment]
I have any idea how I can push changes to this pull request when I am not a contributor, but maybe I found an issue, that failed the build. In current commit history `021-mandelbrot-p5.md` has on the line `31` extra tab before `url: ..`. I think the correct code will be like this:
```
 - title: "Mandelbrot Set in Processing with Navigation"
    author:
      name: "theCCB"
      url: "https://github.com/theCCB"
    url: "https://www.youtube.com/channel/UCQ0kj89I9Bsoop-YNwjUreg"
    source: "https://github.com/theCCB/MandelbrotSetVisualized" 
```

**Pull request merged**
