### PR TITLE
Fix scope of attempts into Coding Challenge 50

### PR DESCRIPTION
**Pull request by nucliweb**
Change the scope of `var attempts` to global into **Processing** and **P5.js** Coding Challenge 50's files.

### CODE REVIEW

**Comment by shiffman** [comment]
I believe `attempts` was intended to be local to the `draw()` loop to give the sketch 1,000 chances *each* time through draw to find a spot for a new circle. Is there something I'm missing that requires it to be global?

**Comment by nucliweb** [comment]
In the block while `attempts ++` it will never reach 1000, since when `count` reaches 9 it leaves the while block, and in the next iteration of the `draw()` function the variable `attempts` is again 0.

So, `if (attempts > 1000)` *(with `noLoop()`)* it will never true.

**Comment by shiffman** [comment]
Yes, I understand. This is in fact the case as I don't want it to be true! It's just protection against an infinite loop in case it tries for 1,000 times and doesn't find a free spot. Thank you again for the contribution!

**Comment by nucliweb** [comment]
Ok, I get it, thanks

**Pull request closed without merging**
