### PR TITLE
Add genetic algorithm written in Rust

### PR DESCRIPTION
**Pull request by mithi**
### Community Contribution

**Link to live project, video, or image:**
- https://medium.com/@mithi/genetic-algorithms-in-rust-for-autonomous-agents-an-introduction-ac182de32aee
- https://github.com/mithi/rusty-genes

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**
https://www.instagram.com/minimithi/

### CODE REVIEW

**Comment by gruselhaus** [comment]
Great!

**Comment by gruselhaus** [comment]
https://www.githubstatus.com/incidents/2y6v4ltq26g7

**Comment by mithi** [comment]
Thanks! @gruselhaus let me know how to make the checks successful so I can update the pull request as needed. I've also allowed edits from maintainers. Thanks again!

**Comment by gruselhaus** [comment]
Merging now. I made sure that the yaml is correct.

**Comment by mithi** [comment]
Thanks for merging @gruselhaus !

**Pull request merged**
