### PR TITLE
added guide for developers

### PR DESCRIPTION
**Pull request by jonnytest1**

### CODE REVIEW

**Comment by shiffman** [comment]
Agreed about consolidating! I don't have a strong preference whether it lives in wiki or markdown files. I might suggest moving the contribution guides to markdown files in the repo itself? People don't seem to look for the wiki and tracking the history/changes for the guides might be nicer in the repo itself?

**Comment by shiffman** [comment]
@gruselhaus what do you think?

**Comment by nilsweb** [comment]
I'm happy as long as it's consistent! 😋

**Comment by gruselhaus** [comment]
I prefer the markdown version.

**Comment by shiffman** [comment]
@gruselhaus agreed, let's move everything and deprecate the wiki?

**Comment by gruselhaus** [comment]
@shiffman https://github.com/CodingTrain/website/wiki/Workflow is this still up to date or should we refer to https://www.youtube.com/playlist?list=PLRqwX-V7Uu6Zu_uqEA6NqhLzKLACwU74X ?

**Comment by nilsweb** [comment]
👍🏻

**Comment by shiffman** [comment]
@gruselhaus that page is definitely not up to date! I would probably prefer pages with the workflow videos and associated links as a "section" under . . tutorials? Courses? #824 😜

**Comment by gruselhaus** [comment]
> @gruselhaus agreed, let's move everything and deprecate the wiki?

Ok. I've opened a new PR. #1523

**Pull request closed without merging**
