### PR TITLE
Contribution: Random tree rings.

### PR DESCRIPTION
**Pull request by ShriRambo**
After viewing the tutorial of polar Perlin noise, I created a sketch which generates tree rings at random. Demo at the following link
   https://shrirambo.github.io/p5Gallery/Resources/Tree%20Rings/blogpost.html
Added a grunge effect to make it a bit more realistic.

### CODE REVIEW

**Comment by gruselhaus** [comment]
This is incredible ❤️

**Comment by ShriRambo** [comment]
Thanks :)

**Comment by shiffman** [comment]
So great, thank you for sharing!

**Comment by ShriRambo** [comment]
Thank you for featuring my work on your webpage. :)

**Pull request merged**
