### PR TITLE
Adding safety-check to prevent "points no iterable" error

### PR DESCRIPTION
**Pull request by Carla-de-Beer**
This error occurs when when the mouse position is off-canvas in the CC_98_QuadTree example code.

### CODE REVIEW

**Comment by shiffman** [comment]
Thanks for this! I think it makes more sense to correct the bug that is in the `QuadTree` class where found returns `undefined` rather than an empty array `[]`. You can see the corrected code here if you want to pull request the same to this repo:

https://github.com/CodingTrain/QuadTree/blob/master/quadtree.js#L148

**Comment by nilsweb** [comment]
@shiffman Should I resolve the conflicts and merge?

**Comment by shiffman** [comment]
@nilsweb yes, though I think it's probably good policy to add a comment when the code differs from the video challenge?

**Comment by nilsweb** [comment]
I added a short comment as suggested!

**Pull request merged**
