### PR TITLE
Contribution added. Epicycles redrawing a user drawn loop.

### PR DESCRIPTION
**Pull request by ilmnarayana**
Project: https://wwl5q1434k.codesandbox.io/
Project Description:
Epicycles redraws a loop which was drawn by the user inside canvas (at least tries if you give a hard one).
The source code has to be refactored a lot and comments and ReadMe file has to be added.
There are three phases when you open the url.
1) where you draw a single loop and hit start. (loop will be closed after drawing)
2) circles trying to fit the shape by increasing number of circles. (you can adjust the number of circles by slider provided and hit start again)
3) where the Epicycles draws the loop
and reset button clears canvas and let you start from phase 1.

### CODE REVIEW

**Comment by shiffman** [comment]
This is fantastic! I'm thinking about doing something similar tomorrow as a follow-up. Did you implement the FT algorithm yourself or use a library? I'm not sure how to best explain and implement the leap from separate x's and y's to (x,y)'s together.

**Comment by ilmnarayana** [comment]
Yeah I implemented FT algorithm myself. My code is little difficult to
understand and my FT implementation is different from yours (I have to
comment it well and lot of refactoring has to be done). But here is a rough
explanation of what I did. You took x and y as separate arrays and
constructed 2 epicycle groups. I converted the points data into polar
coordinates. So I will only store 'r' values for each point (taking canvas
0,0 as origin). The array will contain r values for theta = -pi/2 to pi/2.
And I constructed only 1 epicycle group from it. Hope this helps.

And by the way.. I am so excited that you liked my project!! Ready to help
you any time. (But I am not that good at explaining things😥.. I will try
my best anyway).

**Comment by ilmnarayana** [comment]
Yeah I implemented FT algorithm myself. My code is little difficult to
understand and my FT implementation is different from yours (I have to
comment it well and lot of refactoring has to be done). But here is a rough
explanation of what I did. You took x and y as separate arrays and
constructed 2 epicycle groups. I converted the points data into polar
coordinates. So I will only store 'r' values for each point (taking canvas
0,0 as origin). The array will contain r values for theta = -pi/2 to pi/2.
And I constructed only 1 epicycle group from it. Hope this helps.

And by the way.. I am so excited that you liked my project!! Ready to help
you any time. (But I am not that good at explaining things😥.. I will try
my best anyway).

**Comment by ilmnarayana** [comment]
Hi,
Actually there is no need to convert to polar coordinates, single epicycle
can be formed by slight change in your dft function. Instead of passing
x-coordinate and y-coordinate separately into dft function, you can pass a
array of complex values (x+iy) (or two arrays of x,y) into function. and
any multiplication and addition involved in the function must be changed to
complex multiplication and addition respectively. and you have to change k
values from  (0 to N) to (-C/2 to C/2) where C is number of circles you
want. here is my implementation of your dft function

function dftComplex(x, y, noOfCircles) {
  const X = {};
const N = x.length;
for (let k = -noOfCircles/2; k <= noOfCircles/2; k++) {
    let re = 0;
    let im = 0;
    for (let n = 0; n < N; n++) {
      const phi = (TWO_PI * k * n) / N;
      // This is (x+iy) * (cos(phi)-sin(phi))
      re += ((x[n] * cos(phi)) + (y[n] * sin(phi)));  // only this changes
from normal dft dunction.
      im += ((y[n] * cos(phi)) - (x[n] * sin(phi)));  // only this changes
from normal dft function
    }
    re = re / N;
    im = im / N;
    let freq = k;
    let amp = sqrt(re * re + im * im);
    let phase = atan2(im, re);
    X[k] = { re, im, freq, amp, phase };
  }
  // declare a global variable 'center' to store and get rid of big
stationary circle which is X[0]
  // center = createVector(X[0].re, X[0].im);
  // delete X[0];
  return Object.values(X);
}

and when you create epicycles in script.js use
fourier = dftComplex(x, y, 20);
let arr = epiCycles(0, 0, 0, fourier);  // better to use
epiCycles(center.x, center.y, 0, fourier); to not show the big stationary
circle
let v = createVector(arr.x, arr.y);
path.unshift(v);

**Comment by ilmnarayana** [comment]
Yeah.. you can use it. I am actually very happy to help you. I am a big fan
of your coding challenge videos and this is first time contributing to the
community and I will continue to do it.

Thanks,
ilmnarayana

**Pull request merged**
