### PR TITLE
Added community contribution

### PR DESCRIPTION
**Pull request by Fraasi**

### CODE REVIEW

**Comment by Fraasi** [comment]
Accidently commented in the commit description :)
And I thought I was changing the first pull request, but made a new one and couldn't find a button to remove the first one, so now there's two commits... much to learn how to git still.

**Comment by Fraasi** [comment]
@nilsweb  So what's going on? Is this going to get pulled or rejected, or are we just waiting for something?
If you look here, The formatting works now.
 https://github.com/Fraasi/Rainbow-Code/blob/a0fe05ca0998f6d3a5879c58b1dee556c49944eb/_CodingChallenges/30-phyllotaxis.md

**Comment by meiamsome** [comment]
Hey @Fraasi, sorry for the delay on this - there's quite the backlog of open PRs due to the website being so new, I'll try to get through them over this weekend. For now, I've checked your PR and will merge it now. It looks great, by the way, I especially like the gallery of possibilities!

**Comment by Fraasi** [comment]
@meiamsome No problem, lots of things to do to keep the train moving. The new site looks great, that's why I thought want this up there:)  
I'll take a looksee around the issues if there's anything I could help with.

**Comment by nilsweb** [comment]
@Fraasi I'm really sorry! I somehow broke my Jekyll installation and couldn't get it running again due to some dependency issues so I forgot to merge... 😞 
Thanks @meiamsome for taking over!

**Comment by Fraasi** [comment]
@nilsweb  We're all busy doing the things we do, if I counted all the things I've broken, I wouldn't have build anything . No worries, just wondering. But since you know jekyll, maybe take a look if this is ok? https://github.com/CodingTrain/website/issues/420    
When you have time that is :)

**Pull request merged**
