### PR TITLE
Deployment previews on pull requests

### PR DESCRIPTION
**Pull request by jasonbarry**
I think Coding Train would benefit in having deployment previews on every pull request, that way we can generate an automatic build of the website per PR rather than having to checkout branches locally to review/verify changes.

These are the changes needed to integrate w/ [FeaturePeek](https://featurepeek.com), a deployment preview provider. If the GitHub App is installed (for webhooks), then every subsequent PR will have its own deployment preview.

### CODE REVIEW

**Comment by violetcraze** [comment]
This looks awesome!! Thanks so much for setting this up and I think it'll be a huge help.

I wonder if this would make our Jekyll Build Test redundant? Thoughts?

Also love to get @gruselhaus's opinion because you set up most of our actions so you know more about them then me.

**Comment by gruselhaus** [comment]
Jekyll Build Test would be obsolete, yes. I think that this solution is the best. Thank you @jasonbarry

**Comment by gruselhaus** [comment]
Will remove the jekyll build test after merging this PR.

**Comment by jasonbarry** [comment]
@violetcraze @gruselhaus no problem, and that's great! Please be sure to install the [GitHub App](https://github.com/apps/featurepeek) on this repo (for webhooks) and for at least one person in the Coding Train org to create a free [account](https://dashboard.featurepeek.com) on FeaturePeek – the automation will kick in then.

**Pull request merged**
