### PR TITLE
Optimization changes in Hilbert Curve

### PR DESCRIPTION
**Pull request by KonradLinkowski**

### CODE REVIEW

**Comment by violetcraze** [comment]
Thanks for the suggestions, they look like great changes. However we like to keep the example code as close to the code in the video as possible so people looking for the source code aren't confused. I'd suggest making your own optimized version and then adding that as a community contribution. Here is a guide on how to do that: https://thecodingtrain.com/Guides/community-contribution-guide

**Comment by KobeLiesenborgs** [comment]
Hey @violetcraze thanks for thinking about me! Shame I didn't make this pull request, point is still valid though @KonradLewinski!
Have a nice day both of you!

**Comment by violetcraze** [comment]
Sorry my bad meant to tag @KonradLinkowski. My bad.

**Comment by KobeLiesenborgs** [comment]
No worries! Mistakes happen! Have a nice day though!

**Pull request closed without merging**
