### PR TITLE
Put all of the other tutorials into the website

### PR DESCRIPTION
**Pull request by simon-tiger**

### CODE REVIEW

**Comment by nilsweb** [comment]
Thanks @simon-tiger for starting this! If you have any questions/suggestions, feel free to ask/comment.

**Comment by Merijn-DH** [comment]
Hey Simon, please make sure to use `title: ` instead of `name: `

**Comment by shiffman** [comment]
Just want to say thank you for this contribution @simon-tiger!! I'll let @nilsweb merge when ready.

**Comment by nilsweb** [comment]
@simon-tiger Just give me an @mention when you're ready to merge!

**Comment by meiamsome** [comment]
I have split these out into PRs #1080 #1081 #1082 #1083 #1084 and fixed the linting errors, so am closing this PR.

**Pull request closed without merging**
