### PR TITLE
use CDN for p5.js libs. remove local p5.js files.

### PR DESCRIPTION
**Pull request by Spongman**
re #542

- updates local p5 libs to 0.6.1 CDN versions.
- removes (now) unused p5 files

### CODE REVIEW

**Comment by micuat** [comment]
I tested cc 01 and 02 and they work fine. maybe comment like

```
  // as of p5.js 0.6.0, normal material has to be explicitly selected
  normalMaterial();
```

will be helpful.

**Comment by shiffman** [comment]
I'd like to merge this, any comments or questions before I do? @meiamsome @nilsweb

**Comment by meiamsome** [comment]
No issues here! Looking forward to having 10 million less lines...

**Comment by shiffman** [comment]
Yay!

**Pull request merged**
