### PR TITLE
Added My Version of Asteroids Game

### PR DESCRIPTION
**Pull request by tushar-upadhyay**
Adding Asteroids game with cool sound effects

### Community Contribution

**Link to live project, video, or image:**
https://editor.p5js.org/tusharpg/full/RL9bD0KPB

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**

**Twitter:**

### CODE REVIEW

**Comment by gruselhaus** [comment]
https://www.githubstatus.com/incidents/2wx06v7dbzhg

**Comment by tushar-upadhyay** [comment]
hey @gruselhaus  why my checks are in waiting?

**Comment by gruselhaus** [comment]
Looks like GitHub has an incident in progress regarding GitHub Actions. I will run them locally and merge them.

**Comment by tushar-upadhyay** [comment]
ok

**Comment by gruselhaus** [comment]
Unit tests passed locally so I'm going to merge.

**Comment by tushar-upadhyay** [comment]
thanks @gruselhaus

**Pull request merged**
