### PR TITLE
10Print using JavaScript

### PR DESCRIPTION
**Pull request by Ashikpaul**
Implemented 10Print using vanilla JavaScript with TRIANGLES

Characters used are

"\u25B3", "\u25B2","\u25B6","\u25BC","\u25BD","\u25C0","\u25C1","\u25E2","\u25E3","\u25E4","\u25E5"

### Community Contribution

**Image:**

image

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**  https://www.instagram.com/ashik.paul/

**Twitter:**

### CODE REVIEW

**Comment by gruselhaus** [comment]
This is great!

**Comment by Ashikpaul** [comment]
Thank you @gruselhaus and @shiffman 😍😍.

This was my first real contribution.

**Comment by gruselhaus** [comment]
Welcome to the community 🎉

**Comment by shiffman** [comment]
I love it!!!

**Pull request merged**
