### PR TITLE
Ported ClappingBird to Processing4

### PR DESCRIPTION
**Pull request by spencerstith**
### Community Contribution

Hello, I got this working well with Processing's Audio library and hopefully it will help a little bit to get more people to use it. Unfortunately, there are no sliders native to Processing, so I just had to hard code values for the audio thresholds instead of using sliders like in the original. I made sure these values work well to register clapping, however. I figured this would be better than nothing!

**Link to live project, video, or image:**

Screen Shot 2021-08-22 at 4 47 12 PM
Screen Shot 2021-08-22 at 4 47 26 PM

### Sharing

- [ x ] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**

**Twitter:**

### CODE REVIEW

**Review by gruselhaus — APPROVED** [review]
LGTM

**Comment by gruselhaus** [comment]
Great Work @spencerstith

**Comment by gruselhaus** [comment]
@shiffman is this good to go?

**Comment by shiffman** [comment]
This is incredible, thank you @spencerstith!!

**Pull request merged**
