### PR TITLE
Adding a feature to add recommended community references

### LINKED ISSUE #1340: Suggestion - Add Community Reference Material Section to CC Pages
I'd like to suggest adding a section to the coding challenge pages for community members to add references to other educational videos, articles, or projects (that are not their own).

I think some of this happens in the youtube comments but I've found it can get lost among other comments. It might be a valuable way for people to find additional resources when working on projects.

I had this idea after the latest coding challenge on ray casting when it reminded me of a video about doing the same thing using a command line in c++. Having a section of related references might be a good way to diversify the coding challenge pages and provide options for those working in other languages (programing or non-programming).

[Link to the previously mentioned video](https://www.youtube.com/watch?v=xW8skO7MFYw&t=31s) in case someone is interested.

This idea relates to #1092

### PR DESCRIPTION
**Pull request by gruselhaus**
Thank you @figraham for this suggestion.

Bildschirmfoto 2019-05-10 um 20 30 39
Bildschirmfoto 2019-05-10 um 20 30 47

Fixes #1340

### CODE REVIEW

**Comment by gruselhaus** [comment]
Should we replace the `by` with `suggested by`?

**Comment by nilsweb** [comment]
Great idea! 👍🏻
I'd go with 'suggested by' but either one is fine!

**Comment by figraham** [comment]
Looks good! Thanks @gruselhaus for taking the time to make the change.

**Comment by gruselhaus** [comment]
> Great idea! 👍🏻
I'd go with 'suggested by' but either one is fine!

Working on it already ;)

**Comment by gruselhaus** [comment]
Now with `suggested by`

Bildschirmfoto 2019-05-10 um 21 03 02

**Comment by shiffman** [comment]
Maybe it makes sense to remove "for this Coding Challenge" or "of this Coding Challenge" from the sections as that is assumed?

**Comment by gruselhaus** [comment]
>Maybe it makes sense to remove "for this Coding Challenge" or "of this Coding Challenge" from the sections as that is assumed?
Yes, that makes totally sense.

**Pull request merged**
