### PR TITLE
Spring Force Contribution - Grass

### PR DESCRIPTION
**Pull request by llewan**
Link to demo here: https://editor.p5js.org/leolewan/full/g_Dh6JvL1

### Community Contribution

**Link to live project, video, or image:**
https://editor.p5js.org/leolewan/full/g_Dh6JvL1

### Sharing

- [x ] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:** @leolewan

**Twitter:** @leolewan

### CODE REVIEW

**Comment by gruselhaus** [comment]
This look really cool!

**Comment by llewan** [comment]
@gruselhaus thanks!

**Comment by llewan** [comment]
@gruselhaus I create two commits do you need me to squash them before merge?

**Comment by gruselhaus** [comment]
Nope, PR got merged btw 😅

**Pull request merged**
