### PR TITLE
Added Contribution To CC46 - Asteroids (GyroDodge)

### PR DESCRIPTION
**Pull request by anuraghazra**
I used gyroscope sensor to control the player and added some sound effects too.
**GyroDodge is more fun to play on mobile devices.**

play : https://anuraghazra.github.io/GyroDodge/

### CODE REVIEW

**Comment by gruselhaus** [comment]
@anuraghazra Does it only run on android devices? On my iPhone it didn't work.

**Comment by anuraghazra** [comment]
I don't know because I'm using Android device and I don't have access to an IPhone so i think I might have to consider Support for Safari's javascript deviceorientation api.

**Comment by gruselhaus** [comment]
> Btw can you tell me which Safari version and IPhone you are using?

iPhone X, iOS: 12.1.4

**Comment by anuraghazra** [comment]
Ohh okay, I think the support is not good. 

https://caniuse.com/#search=DeviceOrientation

**Comment by gruselhaus** [comment]
Ok. Let's merge anyway ❤️

**Comment by anuraghazra** [comment]
Okay thanks! i will try to solve the issue if possible.

**Comment by anuraghazra** [comment]
Okay i think i can fix it. looks like IOS devices uses `ondevicemotion` rather than `ondeviceorientation` event.

https://stackoverflow.com/questions/4378435/how-to-access-accelerometer-gyroscope-data-from-javascript

**Pull request merged**
