### PR TITLE
Added Contribution to #78 - Realistic ParticleSystem

### PR DESCRIPTION
**Pull request by anuraghazra**
Wow, this looks amazing, I found that just by adding simple CSS filters to the canvas can make the particles look very blended and smooth. Awesome.......... :100: 

Play around with sliders in the GUI, and also added some cool textures, for example fire and emitters.

demo : https://anuraghazra.github.io/CanvasFun/particleSystem/

```css
canvas {
    filter : blur(3px) contrast(10);
}
```

### CODE REVIEW

**Comment by anuraghazra** [comment]
need help with CI, please someone resolve the issue
sorry for inconvenience

**Comment by anuraghazra** [comment]
extremely sorry for all of the unnecessary commits.

**Comment by meiamsome** [comment]
@anuraghazra This is awesome! Sorry that you had to fight against the linting rules there for a bit but it's just to make sure everything stays reasonable.

Don't worry about the extra commits, I'll squash merge so they're only one :)

**Comment by anuraghazra** [comment]
@meiamsome got it :smiley: 
BTW, in the `Community Contribution Guide` adding a linting guide makes sense because new contributors can get confused by the rules. so adding a CI linting guide can be helpfull for beginners.

**Comment by meiamsome** [comment]
@anuraghazra That's a great idea, would you like to open an issue on here so that we can track it there?

**Comment by anuraghazra** [comment]
Ok!
:heart:

**Comment by shiffman** [comment]
Beautiful work!

**Pull request merged**
