### PR TITLE
Update 124-flocking-boids.md

### PR DESCRIPTION
**Pull request by shalalajun**
I’m a designer studying JavaScript right now with Daniel shiffmans nature of code. 
this is my study site.
And I can not use git well. please consider...
thanks!
[www.1000triangle.com](url)

### CODE REVIEW

**Comment by gruselhaus** [comment]
@shalalajun Thank you for this❤️ I've resolved some conflict and fixed the indentation
 for you. May I merge?

**Comment by shalalajun** [comment]
> Wow Nice... look great ❤️
> Can i use this rendering idea in my EvolutionAquerium Project?
Thank you.!
Please make it a good work ~
If you can, I will also link to my site later!
Do not speak English well. Please understand ~

**Comment by shalalajun** [comment]
> Wow Nice... look great ❤️
> Can i use this rendering idea in my EvolutionAquerium Project?

Thank you.!
Please make it a good work ~
If you can, I will also link to my site later!
Do not speak English well. Please understand ~

**Comment by anuraghazra** [comment]
did you use Inverse Kinematics to create those tails?

**Comment by shalalajun** [comment]
> did you use Inverse Kinematics to create those tails?

Yes, that is correct
I used Inverse Kinematics!
[https://www.youtube.com/watch?v=hbgDqyy8bIw](url)
[https://www.youtube.com/watch?v=sEKNoWyKUA0&list=PL7wAPgl1JVvXZDYBPGfjvgeUQHJFWLPit&index=4](url)

**Comment by anuraghazra** [comment]
Yes, great but i had to consider about the performance because in [EvolutionAquerium](http://anuraghazra.github.io/EvolutionAquerium) i render over 300 creatures at once so i think using kinematics will slow down things pretty much

**Pull request merged**
