### PR TITLE
Add test platform and a simple test to check links in .md files

### PR DESCRIPTION
**Pull request by arisanguinetti**
I've added the jest test platform and also a simple test to check links in all .md files.

I'm sure this could be improved since I'm a beginner in node and jest ;)

Also, keep in mind this test could take some time to run since it will check all links in all .md files.

I think this was on @nilsweb list on #417...

### CODE REVIEW

**Comment by arisanguinetti** [comment]
Forgot to mention that the test is currently not passing since there are many broken links and I was not sure what to do about it (i.e. Should we remove controbutions with a broken link or just remove the reference?)

**Comment by nilsweb** [comment]
This looks very interesting! Thank you! I'll look more into it over the next couple of days but it seems like a good starting point.

**Comment by arisanguinetti** [comment]
@nilsweb thank you! I've taken this approach due to @shiffman's testing videos but, since there's ruby in the repo for Jekyll, tests might be performed using ruby instead of Node.

If you decide to go with Ruby, then we might need to see this gem:
[https://github.com/gjtorikian/html-proofer](https://github.com/gjtorikian/html-proofer)

**Comment by nilsweb** [comment]
Personally, I'd go with Jest anyway since I don't really like Ruby at all and we're just checking content, conventions, etc. and not actual code.

**Comment by shiffman** [comment]
@arisanguinetti thank you so much for this contribution! I have merged #493 which included the full circleci integration in lieu of this one, but I would love for you to contribute there. Thank you again!

**Pull request closed without merging**
