### PR TITLE
Fixed index out of bounds in fluid_utils.js

### LINKED ISSUE #2515: Index is out of bounds in CC_132_FluidSimulation/P5/fluid_utils.js
In the following [code snippet](https://github.com/CodingTrain/website/blob/master/CodingChallenges/CC_132_FluidSimulation/P5/fluid_utils.js#L107):

```
if (x < 0.5) x = 0.5;
if (x > Nfloat + 0.5) x = Nfloat + 0.5;
i0 = Math.floor(x);
i1 = i0 + 1.0;
if (y < 0.5) y = 0.5;
if (y > Nfloat + 0.5) y = Nfloat + 0.5;
j0 = Math.floor(y);
j1 = j0 + 1.0;
```

the variables `i1` and `j1` will be out of bounds of the array if `x` or `y` is set to `Nfloat + 0.5`, as `Nfloat = N`. This means that in worse case `i0 = N`, `i1 = N+1`, `j0 = N` and `j1 = N+1`. This makes us index outside of the array and pollute it with `NaN` values. We should change `Nfloat = N - 2`.

### PR DESCRIPTION
**Pull request by Naxaes**
Fixes #2515.

### CODE REVIEW

**Comment by gruselhaus** [comment]
@shiffman your thougts?

**Review by shiffman — APPROVED** [review]
I'm good with this bug fix!

**Comment by shiffman** [comment]
Oh, and thank you @Naxaes !!

**Comment by gruselhaus** [comment]
Merged with b0fa1b2b366f6f1418c42d1a6073ebfc8fceb0d0

**Pull request closed without merging**
