### PR TITLE
rearranged footer links

### PR DESCRIPTION
**Pull request by GypsyDangerous**
Since the new `back to top` has the same background color as the `shiffman.net` footer link I moved it from the far right to the far left, I don't if this is the best solution but it is the easiest.

Before Before

After After

Full footer after full after

### CODE REVIEW

**Comment by GypsyDangerous** [comment]
Sorry for the poor image quality I can't take screenshots on my computer at work.

**Comment by Fraasi** [comment]
whoops. I noticed this when I first made this for the new site and meant to fix it with more distinct border or drop-shadow, but forgot the whole thing.
I guess this is as good solution as any.

**Comment by GypsyDangerous** [comment]
@Fraasi am I good to merge or should I wait for @vimkat to look at it?

**Comment by Fraasi** [comment]
I don't think the order of the footer links matter. So I think this is good to go, unless you want to wait for some design-wise comment from someone else.
Anyway what I like about this site is that we can change this again next week if this somehow doesn't work for everybody 😃

**Comment by vimkat** [comment]
Looks perfect, @GypsyDangerous! 👍

**Pull request merged**
