### PR TITLE
Adding my community contribution

### PR DESCRIPTION
**Pull request by simon-tiger**
I'm adding my example, where you can add and remove boundaries.

### CODE REVIEW

**Comment by JohnyDL** [comment]
You didn't save your own version you've just submitted one of Shifman's sketches ,,, it's also useful to post the link to your vesion when submitting the pull so it's easier to check out ;) hope this helps

>     url: "https://editor.p5js.org/codingtrain/present/nf42TaECk"
>     source: "https://editor.p5js.org/codingtrain/sketches/nf42TaECk"

**Comment by simon-tiger** [comment]
OK, I'll fix it!!

**Comment by simon-tiger** [comment]
Fixed!

**Comment by gruselhaus** [comment]
Thank you Simon.

**Comment by JohnyDL** [comment]
Cool again linking for the person that actually has write permissions ^_^ https://editor.p5js.org/simontiger/present/ugHX4yKQC

**Pull request merged**
