### PR TITLE
Add Hexapod Robot Visualizer with Javascript

### PR DESCRIPTION
**Pull request by mithi**
### Community Contribution

**Link to live project, video, or image:**

40 second demo: https://www.youtube.com/watch?v=FxjfTUj2Dk0
live app: hexapod.netlify.app/
source code readme: https://github.com/mithi/hexapod

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**
https://www.instagram.com/minimithi/

### CODE REVIEW

**Comment by mithi** [comment]
This is the error: 
```
    064.1-forward-kinematics.md
      ✕ is formatted correctly (5 ms)
      ○ skipped has valid YAML layout and types
      ○ skipped title matches internal numbering
      ○ skipped Has a unique video_id
      ○ skipped has a valid repository to web_editor mapping
      ○ skipped has a valid web_editor to repository mapping
      YouTube links
        ○ skipped encountered a declaration exception
```

**Comment by mithi** [comment]
I can't seem to pinpoint where the build is failing. Please let me know and I'll fix it immediately. Thanks!

**Comment by violetcraze** [comment]
I think that should fix it. It was complaining about an extra line at the bottom of the file. It can be kinda hard to dig through the test reports to find the error messages. For future information you can scroll all the way down to the bottom and it should have more info. Looks like a cool project. Thanks for sharing!

**Comment by mithi** [comment]
Thanks for catching and fixing the error @violetcraze ! 😄

**Pull request merged**
