### PR TITLE
Added python code for Double Pendulum

### PR DESCRIPTION
**Pull request by manojtummala**
### Community Contribution

**Link to live project, video, or image:**

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**

**Twitter:**

### CODE REVIEW

**Comment by manojtummala** [comment]
> ### Community Contribution
> **Link to live project, video, or image:**
> 
> ### Sharing
> * [x]  I would be happy to have my project shared on The Coding Train's social media!
> 
> **Instagram:**
> 
> **Twitter:**

I am just a beginner and created a game in python with some help.. it is not using pygame...  but just want you guys to get a look at my progress..

**Comment by manojtummala** [comment]
This game "space arena" is similar to that of "Asteroids" which you have created.. so thought of letting you know of this...

**Comment by violetcraze** [comment]
Thanks for sharing your creation! However we like to have links to viewer projects instead of adding them directly to this repository. Could you put the code into another repository and then add a link?

Here's a link to a guide: https://thecodingtrain.com/Guides/community-contribution-guide.
Or a video if you prefer: https://youtu.be/fkIr0inoQ7Y

**Comment by violetcraze** [comment]
Closing due to inactivity. Happy to reopen if you make suggested changes or for discussion.

**Pull request closed without merging**
