### PR TITLE
Added CC132 - fluid simulation

### PR DESCRIPTION
**Pull request by blinkityblank**

### CODE REVIEW

**Comment by shiffman** [comment]
Hmmm, this should pass now that I added the code. . . is a p5.js version required? @nilsweb @meiamsome?

**Comment by shiffman** [comment]
i've checked this and I think it's ok going to force merge 😬

**Comment by nilsweb** [comment]
Sorry, I wanted to look at it all day but unfortunately didn't got to it.
Anyways, looks good and should work! I can't see why the test fails however... 🤔 Maybe @meiamsome might be able to figure it out... 😬

**Comment by meiamsome** [comment]
Tests are failing because @blinkityblank's master is not in line with current master and so was missing the folder, when in our master it is fine. The merge of master in the commit history here is from their master and not ours and so still missed the files.

Also related is that CircleCI continues to not provide the incredibly useful feature of running tests on the result of merging the code into the given branch (See for reference https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/24 and other places), which would have shown up as this test working correctly after the files had been added.

**Pull request merged**
