### PR TITLE
add eg

### PR DESCRIPTION
**Pull request by ajuancer**
### Community Contribution
A remix of the data and APIs course example, hosted on [https://selfying-the-weather.herokuapp.com](https://selfying-the-weather.herokuapp.com)

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

### CODE REVIEW

**Review by violetcraze — APPROVED** [review]
Love all the rainbows! 🌈🌈🌈

**Comment by ajuancer** [comment]
thanks @violetcraze 😄

**Comment by shiffman** [comment]
This is amazing! Great work! tagging @joeyklee as you will love to see this!  https://selfying-the-weather.herokuapp.com/

**Comment by ajuancer** [comment]
thank you @shiffman!!

**Comment by joeyklee** [comment]
Wow! This is exciting! Thanks for the acknowledgements <3 keep up the great work @ajuancer !

**Comment by ajuancer** [comment]
thank you too @joeyklee!!

**Pull request merged**
