### PR TITLE
p5.js Unikitty Flag

### PR DESCRIPTION
**Pull request by leimapapa**
Link to demo here: https://editor.p5js.org/leimapapa/present/CEhgbv3Qy

### Community Contribution

**Link to live project, video, or image:**

### Sharing

- [x] I would be happy to have my project shared on The Coding Train's social media!

**Instagram:**

**Twitter:**

### CODE REVIEW

**Comment by shiffman** [comment]
I am so excited about this port! I couldn't get it to run, however, can you double check it?

**Comment by leimapapa** [comment]
It's working for me, but only in Chrome. Not super familiar with toxiclibs.
[image: image.png]

I made have a (better?) version that uses Matter.js instead.
I didn't submit it yet because I still have it layering a transparent
matter.js canvas under a p5.js canvas.

But it works across all browsers, so 🤷‍♂️

Full page version:   https://editor.p5js.org/leimapapa/present/QvME_a9-G
Editor version: https://editor.p5js.org/leimapapa/sketches/QvME_a9-G

-Sam

**Comment by shiffman** [comment]
Wow, this is incredible!! I wonder if this would make sense as an official code port of the example rather than a community contribution? But I'd certainly want to make sure that @leimapapa gets credit! Thoughts @gruselhaus @violetcraze?

**Comment by leimapapa** [comment]
I refactored my matter.js version to only be only one canvas and use p5 as
the renderer.

Editor view: https://editor.p5js.org/leimapapa/sketches/-vrNNaQJA

Full view: https://editor.p5js.org/leimapapa/present/-vrNNaQJA

**Comment by gruselhaus** [comment]
@shiffman @violetcraze how do you think if we label community ports in the future on the code variations dropdown itself?

**Comment by amnindersingh12** [comment]
@leimapapa wonderful sar 😍😍 i would like yo create my own version too ..

**Review by violetcraze — APPROVED** [review]
Merging as is but will come back to this when #2817 is resolved. Sorry it took so long to add this to the site.

**Pull request merged**
